<?php
/**
 * English language file for groupmanager plugin
 *
 * @author Harald Ronge <harald@turtur.nl>
 * base on groupmgr by Alex Forencich <alex@alexforencich.com>
 */

// menu entry for admin plugins
$lang['menu'] = 'Group Manager';

// custom language strings for the plugin
$lang['notauthorized'] = 'Error: not authorized';
$lang['updatesuccess'] = 'Updated successfully';
$lang['updatefailed'] = 'Update failed';
$lang['menu'] = 'User Manager';
$lang['btn_update_group'] = 'Update group';

//stolen from usermanager
// custom language strings for the plugin
$lang['noauth']      = '(user authentication not available)';
$lang['nosupport']   = '(user management not supported)';

$lang['badauth']     = 'invalid auth mechanism';     // should never be displayed!

$lang['user_id']     = 'User';
$lang['user_pass']   = 'Password';
$lang['user_name']   = 'Real Name';
$lang['user_mail']   = 'Email';
$lang['user_groups'] = 'Groups';

$lang['field']       = 'Field';
$lang['value']       = 'Value';
$lang['add']         = 'Add User';
$lang['delete']      = 'Delete';
$lang['delete_selected'] = 'Delete selected user';
$lang['edit']        = 'Edit user';
$lang['edit_prompt'] = 'Edit this user';
$lang['modify']      = 'Save changes to user';
$lang['search']      = 'Search for user';
$lang['search_prompt'] = 'Search with filter-values';
$lang['search_default_group'] = 'Show only group members';
$lang['clear']       = 'Show everybody';
$lang['filter']      = 'Filter list with criteria';

$lang['summary']     = 'Displaying users %1$d-%2$d of %3$d found. %4$d users total.';
$lang['nonefound']   = 'No users found. %d users total.';
$lang['delete_ok']   = '%d users deleted';
$lang['delete_fail'] = '%d failed deleting.';
$lang['update_ok']   = 'User updated successfully';
$lang['update_fail'] = 'User update failed';
$lang['update_exists'] = 'User name change failed, the specified user name (%s) already exists (any other changes will be applied).';
$lang['add_without_form'] = 'Trying to add user without form!';
$lang['cant_delete_yourself'] = "You can't delete yourself!";
$lang['cant_delete_if_more_groups'] = "User is part of other groups outside of this working group and can not be deleted";

$lang['start']  = 'start';
$lang['prev']   = 'previous';
$lang['next']   = 'next';
$lang['last']   = 'last';

// added after 2006-03-09 release
$lang['edit_usermissing'] = 'Selected user not found, the specified user name may have been deleted or changed elsewhere.';
$lang['user_notify'] = 'Notify user';
$lang['note_notify'] = 'Notification emails are only sent if the user is given a new password.';
$lang['note_group'] = 'New users will be added to the default group (%s)';
$lang['note_pass'] = 'The password will be autogenerated if the field is left empty and notification of the user is enabled.';
$lang['add_ok'] = 'User added successfully';
$lang['add_fail'] = 'User addition failed';
$lang['notify_ok'] = 'Notification email sent';
$lang['notify_fail'] = 'Notification email could not be sent';

// required fields
$lang['mail_required'] = "Mail is required field!";
$lang['user_must_be_notified_with_generated_pwd'] = "When generating a password the user must be notified! Choose a password yourself or check '".$lang['user_notify']."'.";

//Setup VIM: ex: et ts=4 enc=utf-8 :
