# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 08 Mar 2016 07:29:59 +0000
*	@ALL	0
*	@user	0
*	@admin	16
start	@ALL	1
