<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: xiaohui
 * Date: Sun, 22 Jan 2017 11:26:24 +0800
 */

$conf['title'] = '松霖知识库';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['youarehere'] = 1;
$conf['signature'] = '';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['authtype'] = 'authmysql';
$conf['passcrypt'] = 'md5';
$conf['superuser'] = '@admin';
$conf['manager'] = '@admin';
$conf['profileconfirm'] = 0;
$conf['disableactions'] = 'profile_delete,rss,source,export_raw';
$conf['securecookie'] = 0;
$conf['usewordblock'] = 0;
$conf['relnofollow'] = 0;
$conf['mailguard'] = 'none';
$conf['mediarevisions'] = 0;
$conf['refcheck'] = 0;
$conf['htmlmail'] = 0;
$conf['updatecheck'] = 0;
$conf['fnencode'] = 'utf-8';
$conf['dnslookups'] = 0;
$conf['proxy']['user'] = 'solux';
$conf['proxy']['pass'] = '<b>dG9vcg==';
$conf['plugin']['authmysql']['server'] = 'localhost';
$conf['plugin']['authmysql']['user'] = 'root';
$conf['plugin']['authmysql']['password'] = 'toor';
$conf['plugin']['authmysql']['database'] = 'wiki';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['statdisplay']['accesslog'] = 'wiki.log';
$conf['plugin']['statdisplay']['lines'] = 1000;
$conf['plugin']['wrap']['darkTpl'] = 1;
$conf['plugin']['groupmanager']['forbidden_groups'] = 'user';
$conf['plugin']['groupmanager']['allow_add_user'] = '1';
$conf['plugin']['groupmanager']['allow_delete_user'] = '1';
$conf['plugin']['smtp']['smtp_host'] = 'localhost';
$conf['plugin']['smtp']['auth_pass'] = 'meng10dan18';
$conf['plugin']['smtp']['debug'] = '1';
$conf['plugin']['statistics']['db_user'] = 'root';
$conf['plugin']['statistics']['db_password'] = 'toor';
$conf['plugin']['statistics']['db_database'] = 'logs';

// end auto-generated content
